# Default values for homeowners.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: test/spring-api
  tag: latest
  pullPolicy: Always
  imagePullSecret: docker-key
  environment: Development

service:
  name: spring-api
  type: ClusterIP or NodePort or Loadbalancer
  externalPort: 80
  internalPort: 80
ingress:
  enabled: true
  hosts:
    - test.api.spring.com
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/rewrite-target: /
  tls:
    - secretName: tls-secret
      hosts:
        - test.api.spring.com
tls:
  enabled: false
resources: {}
